#pragma once

#define VREN_NAME ("vren")
#define VREN_VERSION VK_MAKE_VERSION(1, 0, 0)
#define VREN_MAX_FRAME_COUNT 4

#define VREN_MATERIAL_DESCRIPTOR_SET      0
#define VREN_LIGHTS_ARRAY_DESCRIPTOR_SET  1

#define VREN_MATERIAL_ALBEDO_TEXTURE_BINDING  0
#define VREN_MATERIAL_MATERIAL_STRUCT_BINDING 1

#define VREN_POINT_LIGHTS_BINDING       0
#define VREN_DIRECTIONAL_LIGHTS_BINDING 1

#define VREN_DESCRIPTOR_SET_POOL_SIZE 32
