name: Sphinx docs

on:
  push:
    branches: [ "master" ]
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  build-docs:
    name: "Build Sphinx docs"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
    
      - name: "Install Python dependencies"
        working-directory: ./docs
        run: pip install -r requirements.txt
    
      - name: "Build Sphinx docs"
        working-directory: ./docs
        run: sphinx-build -b html . _build
    
      - name: "Commit gh-pages"
        working-directory: ./docs
        run: |
          git clone https://github.com/$GITHUB_REPOSITORY.git --branch gh-pages --single-branch gh-pages
          cp -r _build/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update" -a || true
          
      - name: "Push gh-pages"
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: .
          github_token: ${{ secrets.GITHUB_TOKEN }}
